pipeline:
  build:
    image: node:7
    commands:
      - cd client
      - npm config set registry https://registry.npm.taobao.org
      - npm install --no-optional
      - yarn run build
      - sudo docker cp $(sudo docker ps -alq):$PWD/build /var/www/react/  
