pipeline:
  build:
    image: node:7
    volumes:
      - ~/react:/temp/build
    commands:
      # - cd client
      # - npm config set registry https://registry.npm.taobao.org
      # - npm install --no-optional
      # - yarn run build
      - echo 'test' > /temp/build/1.txt
      - mv $PWD/build /temp/build
