pipeline:
  build:
    image: node:7
    volumns:
      - /var/www/react:${PWD}/
    commands:
      - cd client
      - npm config set registry https://registry.npm.taobao.org
      - npm install --no-optional
      - yarn run build
